# Generated by Django 3.0.7 on 2020-07-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_com', '0005_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
