# Generated by Django 3.0.7 on 2020-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_com', '0006_auto_20200712_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
